version: 2.1
jobs:
  test:
    working_directory: ~/nodejs-serverless-jest
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run: yarn install
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: Jest
          command: |
            mkdir -p test-results/jest
            yarn run jest
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
      - store_test_results:
          path: test-results

workflows:
  version: 2
  unit-tests:
    jobs:
      - test

